# Installs the xqueue watcher code and supervisor scripts.
# The watcher can watch one or many queues and dispatch submissions
# to the appropriate grader which lives in a separate SCM repository.

- name: Install application requirements
  pip:
    requirements: "{{ xqwatcher_requirements_file }}"
    virtualenv: "{{ xqwatcher_app_dir }}/venvs/{{ xqwatcher_service_name }}"
    state: present
  become: true
  become_user: "{{ xqwatcher_user }}"
  tags:
    - install
    - install:app-requirements

- name: Write out course config files
  template:
    src: "edx/app/xqwatcher/conf.d/course.json.j2"
    dest: "{{ xqwatcher_conf_dir }}/conf.d/{{ item.COURSE }}.json"
    owner: "{{ xqwatcher_user }}"
    group: "{{ xqwatcher_user }}"
    mode: "0644"
  with_items: "{{ XQWATCHER_COURSES }}"
  tags:
    - install
    - install:configuration

- name: Write supervisord config
  template:
    src: "edx/app/supervisor/conf.d/xqwatcher.conf.j2"
    dest: "{{ xqwatcher_supervisor_available_dir }}/xqwatcher.conf"
    group: "{{ xqwatcher_user }}"
    mode: "0650"
  tags:
    - install
    - install:configuration

- name: Enable supervisor script
  file:
    src: "{{ xqwatcher_supervisor_available_dir }}/xqwatcher.conf"
    dest: "{{ xqwatcher_supervisor_cfg_dir }}/xqwatcher.conf"
    state: link
    force: yes
  when: not disable_edx_services
  tags:
    - install
    - install:configuration

- name: Update supervisor configuration
  shell: "{{ xqwatcher_supervisor_ctl }} -c {{ xqwatcher_supervisor_app_dir }}/supervisord.conf update"
  when: not disable_edx_services
  tags:
    - manage
    - manage:update

- name: Restart xqwatcher
  supervisorctl:
    name: "{{ xqwatcher_service_name }}"
    supervisorctl_path: "{{ xqwatcher_supervisor_ctl }}"
    config: "{{ xqwatcher_supervisor_app_dir }}/supervisord.conf"
    state: restarted
  when: not disable_edx_services
  become_user: "{{ xqwatcher_user }}"
  tags:
    - manage
    - manage:update
